# Site settings
title: zuzhi
email: 476513451@qq.com
description: > # this means to ignore newlines until "baseurl:"
  think do write
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: huzuzhi
github_username:  zuzhi

# Build settings
markdown: kramdown
