# Site settings
title: zuzhi's github pages
email: 
description: > # this means to ignore newlines until "baseurl:"
  This is a description. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: zuzhi
github_username:  zuzhi

# Build settings
markdown: kramdown
